### ISSUE TITLE
[BUG][PHP] hydra model properties with @ prefix are removed which can result in method duplicates and invalid classes

### ISSUE THREAD

**Issue by warmwaterkruik** [swagger-api/swagger-codegen-generators#1041]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

When generating PHP client classes from a schema generated by [API Platform](https://api-platform.com/docs/core/) you can get invalid PHP classes because of clashing method names. A Hydra model can have "@id" and "id" as properties resulting in two clashing getId methods

##### generator version

3.0.35-SNAPSHOT
3.0.34

##### OpenAPI declaration file content or url

```yaml
TicketTemplate.Category.jsonld:
      type: object
      description: ''
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        id:
          readOnly: true
          type: string
          format: uuid
          nullable: true
        name:
          type: string

```

##### Steps to reproduce

1. `wget bookshop-api.yaml`
2. `java -jar swagger-codegen-cli.jar generate --lang php --input-spec bookshop-api.yaml --output ${PWD}`
