### ISSUE TITLE
`@NotNull` is added by default for fields that are not required 

### ISSUE THREAD

**Issue by yeikel** [swagger-api/swagger-codegen-generators#1295]
Given the following step: 

Swagger Definition:

```yml

address_start_date:
        type: string
        format: 'date-time'
        example: "2011-12-03 10:15:30"
        description: |
          Start Date for address

```

swagger-codegen-maven-plugin  `3.0.56` generates the following model: 

```java
   /**
   * Start Date for address 
   * @return addressStartDate
  **/
  @Valid
  @Schema(description = "Start Date for address ")
  public LocalDateTime getAddressStartDate() {
    return addressStartDate;
  }

```

While swagger-codegen-maven-plugin  `3.0.57` generates this: 

```java

   /**
   * Start Date for address 
   * @return addressStartDate
  **/
  @NotNull // <--- This is added by default
  @Valid
  @Schema(description = "Start Date for address ")
  public LocalDateTime getAddressStartDate() {
    return addressStartDate;
  }
```

It seems that this is what introduced with https://github.com/swagger-api/swagger-codegen-generators/pull/1291
