### ISSUE TITLE
[java jaxrs-jersey] default values are never generated in annotations

### ISSUE THREAD

**Issue by tomzo** [swagger-api/swagger-codegen-generators#166]
In all operations I have in my 3.0 spec, swagger-codegen never emits `@DefaultValue` annotation, although it exists on parameter definitions.

For parameter in operation like this:
```yaml
    put:
      operationId: putExactResultZip
      tags:
        - results
      parameters:
        - name: failed
          in: query
          schema:
            type: boolean
            default: false
```
Emitted code for parameter is
```java
,@Parameter(description = "") @QueryParam("failed") Boolean failed
```
While I would expect it to include the default value:
```java
,@Parameter(description = "") @QueryParam("failed") @DefaultValue("false") Boolean failed
```

It does not matter what is the type of default, in a big project with many uses of `default` I see no `@DefaultValue` annotations in generated code.

## Version info

Swagger-codegen (build from 3.0.0 release 713d52883cf320d46fb1a555c63e8ad99f78c16e), which is using 1.0.0 release of swagger-codegen-generators.
