### ISSUE TITLE
[java] inconsistent behaviour when generating enum names

### ISSUE THREAD

**Issue by narkaTee** [swagger-api/swagger-codegen-generators#246]
I've noticed a inconsistency when generating enum names in java.
The generator creates a different name for enums if there is only one options.

Reproduction Repo: https://github.com/narkaTee/swagger-codegen-enum-repro

For Example take the following swagger definitions (v2):
```yaml
definitions:
  fooBar:
    type: object
    properties:
      foo:
        type: string
        enum: ["foo bar"]
  herp:
    type: object
    properties:
      bar:
        type: string
        enum: ["foo bar", test]
```

Swagger codegen generates the enum for the first object with only "BAR" as enum value [as seen here](https://github.com/narkaTee/swagger-codegen-enum-repro/blob/50f9d4da1cfb379a35327d56b2ce6158dff61f28/generated/src/main/java/io/swagger/client/model/FooBar.java#L34).
The second object on the other hand has "FOO_BAR" as an enum value [as seen here](https://github.com/narkaTee/swagger-codegen-enum-repro/blob/50f9d4da1cfb379a35327d56b2ce6158dff61f28/generated/src/main/java/io/swagger/client/model/Herp.java#L34-L35).

Using underscores instead of spaces results in the same behavior.
