### ISSUE TITLE
Authentication headers are not geneated for Swift5

### ISSUE THREAD

**Issue by aliaksandrb** [swagger-api/swagger-codegen-generators#696]
Hi,

Am I right that the whole `securitySchemes` is not supported by codegen for Swift5?

I have tried different openapi 3 definitions, such as:
```yaml
  securitySchemes:
    token:
      type: apiKey
      in: header
      name: Authorization

+ in path definition

    get:
      security:
        - token: []
```

and

```yaml
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

+ in path definition

    get:
      security:
        - bearerAuth: []
```

But none of them generated code to provide a value for an authentication headers. They do generate documentation though, for instance:
```yaml
    /**
     Get some stuff
     - GET /my_endpoint

     - API Key:
       - type: apiKey Authorization 
       - name: token
```

By looking into templates here: https://github.com/swagger-api/swagger-codegen-generators/tree/b5ef36779ca6d251a4899a2d0d288880d8e6fd70/src/main/resources/handlebars/swift5
it looks like it is just not supported.

Is it correct or I just messed up with definitions? 

Thank you!
