### ISSUE TITLE
Java: Generated @Pattern annotation does not encode the pattern

### ISSUE THREAD

**Issue by dirk-olmes** [swagger-api/swagger-codegen-generators#854]
My spec contains a pattern validation for a schema:
```
components:
  schemas:
    myCustomId:
      type: string
      pattern: '^[A-Z]\d{9}$'
```
When generating code the `beanValidationCore.mustache` uses the literal pattern from the Spec which leads to compile errors because the `\` character is not escaped in the generated Java String.

I know I can just put the properly escaped pattern into the spec. But from a modeling/specification point of view I don't want to deal with Java specifics. IMHO that's the concern of the code generator for the platform.
