### ISSUE TITLE
[Python] NameError exception and error in setter in model

### ISSUE THREAD

**Issue by RostislavU** [swagger-api/swagger-codegen-generators#869]
I have part of swagger yaml:

```yaml
UserDto:
    description: User with role property
    properties:
      roles:
        additionalProperties:
          items:
            enum:
            - HEAD
            - SIGNER
            type: string
          type: array
        description: User role 
        type: object
      departmentId:
        description: departmentId
        format: int32
        type: integer
      id:
        description: id
        format: uuid
        type: string
      login:
        description: login
        type: string
    title: UserDto
    type: object
```

swagger-codegen-generators-2.4.18.jar build model UserDto for me with this setter:

```python
    @roles.setter
    def roles(self, roles):
        allowed_values = [HEAD, SIGNER]  # noqa: E501
        if not set(conclusion_requests_and_roles()).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid keys in `roles` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(roles.keys()) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._roles = roles
```
First problem: I am getting an exception "NameError"
