### ISSUE TITLE
"pipeDelimeted" query parameter format generates invalid node-fetch code

### ISSUE THREAD

**Issue by FabianTe** [swagger-api/swagger-codegen-generators#887]
Hi,

setting the `style` parameter of a query parameter to `pipeDelimited` generates invalid `typescript-fetch` code.

### Example Property

```yml
- name: searchIn
    in: query
    description: Ids of the columns to search in
    required: true
    style: pipeDelimited
    explode: false
    schema:
    type: array
    items:
        type: integer
```

```
api.ts(7404,87): error TS2551: Property 'pipe' does not exist on type '{ csv: string; ssv: string; tsv: string; pipes: string; }'. Did you mean 'pipes'?
```

### Generated code 

This is the generated `COLLECTION_FORMATS` object:

```ts
/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};
```

And this is the code that tries to access an invalid property of `COLLECTION_FORMATS`:

```ts
if (searchIn) {
    localVarQueryParameter['searchIn'] = searchIn.join(COLLECTION_FORMATS["pipe"]);
}
```
